---
- name: Create the kamal user
  ansible.builtin.user:
    name: kamal
    shell: /bin/bash
    groups: sudo
    state: present

- name: Set password for kamal user from environment variable
  ansible.builtin.user:
    name: kamal
    password: "{{ lookup('env', 'KAMAL_USER_PASSWORD') | password_hash('sha512') }}"
  no_log: true

- name: Ensure kamal user uses a password for sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: ^kamal ALL=\(ALL\).*
    line: kamal ALL=(ALL) ALL
    validate: visudo -cf %s

- name: Create .ssh directory for kamal user
  become: true
  ansible.builtin.file:
    path: /home/kamal/.ssh
    state: directory
    owner: kamal
    group: kamal
    mode: "0700"

- name: Copy authorized SSH key to kamal user's home directory
  ansible.builtin.copy:
    remote_src: true
    src: /root/.ssh/authorized_keys
    dest: /home/kamal/.ssh/authorized_keys
    owner: kamal
    group: kamal
    mode: "0600"

- name: Remove authorized_keys file from root's SSH configuration
  ansible.builtin.file:
    path: /root/.ssh/authorized_keys
    state: absent
