---
- name: Check and load vars file
  ansible.builtin.import_tasks: check_vars.yml

- name: Setup system security
  ansible.builtin.import_tasks: security.yml

- name: Setup firewall
  ansible.builtin.import_tasks: firewall.yml
  when: skip_ufw_config is not defined or not skip_ufw_config

- name: Install apt packages
  ansible.builtin.import_tasks: apt_packages.yml

- name: Setup docker
  ansible.builtin.import_tasks: docker.yml
  when: (install_docker is defined and install_docker) or (install_docker is not defined)
