#!/bin/bash

set -e
CMD=$1
WORKDIR=$(pwd)

main() {
  __precheck
}

__precheck() {
  __check_cmd python
  __check_cmd ansible
}

__check_cmd() {
  if ! command "$1" --version &> /dev/null; then
      echo "$1 is not installed. Please install $1 first."
      exit 1
  fi
}

main
